// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentMangmentSystem.Models;

#nullable disable

namespace StudentMangmentSystem.Migrations
{
    [DbContext(typeof(StudentMangmentSystemDbContext))]
    [Migration("20250831103845_add-migration initial")]
    partial class addmigrationinitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentMangmentSystem.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnrolled")
                        .HasColumnType("datetime2");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.HasKey("StudentId", "CourseId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.user", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.Admin", b =>
                {
                    b.HasBaseType("StudentMangmentSystem.Models.user");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.Student", b =>
                {
                    b.HasBaseType("StudentMangmentSystem.Models.user");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.SuperAdmin", b =>
                {
                    b.HasBaseType("StudentMangmentSystem.Models.user");

                    b.ToTable("SuperAdmins", (string)null);
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.Admin", b =>
                {
                    b.HasOne("StudentMangmentSystem.Models.user", null)
                        .WithOne()
                        .HasForeignKey("StudentMangmentSystem.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.Student", b =>
                {
                    b.HasOne("StudentMangmentSystem.Models.user", null)
                        .WithOne()
                        .HasForeignKey("StudentMangmentSystem.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentMangmentSystem.Models.SuperAdmin", b =>
                {
                    b.HasOne("StudentMangmentSystem.Models.user", null)
                        .WithOne()
                        .HasForeignKey("StudentMangmentSystem.Models.SuperAdmin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
